// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hhfxdfdrjjasbrekqzwi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhoZnhkZmRyamphc2JyZWtxendpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4MDkzMjUsImV4cCI6MjA2NzM4NTMyNX0.pazyd3jphxBF13wmslS1CUT_l-ARqr4fi1PFWXc7Cys";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});